graph TD

    IQimportDeclaration["Import, Declaration"]
    IQimportDeclarationToken["'Import'"]
    IQimportPath["Import, Pathname"]
    IQimportPathToken["'github.com/bblfsh/sdk'"]

    IQimportDeclaration-->IQimportDeclarationToken
    IQimportDeclaration-->IQimportPath
    IQimportPath -->IQimportPathToken

